//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by 박서연 on 2024/09/25.
//

import ProjectDescription

let workspace = Workspace(
    name: "simi",
    projects: [
        "Projects/SimiApp",
        "Projects/Core",
        "Projects/DesignSystem",
        "Projects/Feature/Coordinator",
        "Projects/Feature/Scene"
    ],
    generationOptions: .options(
      autogeneratedWorkspaceSchemes: .enabled()
    )
)

